; WLED Ultimate - MoonModules integration channel
; Source: MoonModules/WLED-MM:mdev

[ultimate_mm]
build_flags =
  -D WLED_ULTIMATE=1
  -D WLED_ULTIMATE_MM=1
  -D WLED_ULTIMATE_CHANNEL=\"mm\"

[env:ultimate_esp32_4mb]
extends = env:esp32_4MB_V4_M
build_flags =
  ${env:esp32_4MB_V4_M.build_flags}
  ${ultimate_mm.build_flags}

[env:ultimate_esp32_4mb_eth]
extends = env:esp32_4MB_V4_S_eth
build_flags =
  ${env:esp32_4MB_V4_S_eth.build_flags}
  ${ultimate_mm.build_flags}

[env:ultimate_esp32_16mb_eth]
extends = env:esp32_16MB_V4_M_eth
build_flags =
  ${env:esp32_16MB_V4_M_eth.build_flags}
  ${ultimate_mm.build_flags}

[env:ultimate_esp32s3_8mb_psram]
extends = env:esp32S3_8MB_PSRAM_M_opi
build_flags =
  ${env:esp32S3_8MB_PSRAM_M_opi.build_flags}
  ${ultimate_mm.build_flags}

[env:ultimate_esp32s3_16mb_hub75]
extends = env:esp32S3_16MB_PSRAM_M_HUB75
build_flags =
  ${env:esp32S3_16MB_PSRAM_M_HUB75.build_flags}
  ${ultimate_mm.build_flags}
